language: generic
notifications:
  email:
    on_failure: change
    on_success: never
install:
- "git clone https://github.com/vim/vim vim && pushd vim && make && sudo make install && popd"
script: make testversion
